#!/bin/bash

set -ex

PROJECT_NAME=async-box-bot

python -m copier --defaults . $PROJECT_NAME
cd $PROJECT_NAME

docker-compose up -d
sleep 10

curl --silent --fail http://localhost:8000/healthcheck || exit 1
