#!/bin/bash

set -ex

PROJECT_NAME=bot-example
python -m copier copy --force --trust  . $PROJECT_NAME
cd $PROJECT_NAME

docker compose up -d
sleep 10

curl --show-error --fail http://localhost:8000/healthcheck || exit 1
