"""init

Revision ID: 765dcfed2d16
Revises:
Create Date: 2025-06-11 16:30:02.133576

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""

from alembic import op
import sqlalchemy as sa


revision = "765dcfed2d16"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("record_data", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample_record")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sample_record")
    # ### end Alembic commands ###
